# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [1]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration 

In [3]:
np.version.version

'1.19.2'

#### Q3 : Créer un vecteur nul de taille 10

In [5]:
np.zeros(10).reshape((10, 1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [10]:
v = np.zeros(10)
v[3] = 1
print(v.reshape(10, 1))

[[0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [13]:
z = np.arange(10, 51).reshape(41, 1)

array([[10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49],
       [50]])

#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [16]:
z = z[::-1]
print(z)

[[50]
 [49]
 [48]
 [47]
 [46]
 [45]
 [44]
 [43]
 [42]
 [41]
 [40]
 [39]
 [38]
 [37]
 [36]
 [35]
 [34]
 [33]
 [32]
 [31]
 [30]
 [29]
 [28]
 [27]
 [26]
 [25]
 [24]
 [23]
 [22]
 [21]
 [20]
 [19]
 [18]
 [17]
 [16]
 [15]
 [14]
 [13]
 [12]
 [11]
 [10]]


#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [35]:
np.random.randint(low = 8, size = (3, 3)) 

array([[2, 7, 7],
       [5, 4, 6],
       [1, 2, 5]])

#### Q8 : Créer une matrice identié 3x3 

In [20]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [34]:
np.random.randint(low = 100, size = (3, 3, 3))

array([[[70, 21, 61],
        [19, 74, 73],
        [80, 12, 15]],

       [[42, 61, 18],
        [ 5, 89, 12],
        [98, 49, 28]],

       [[52, 75, 16],
        [57, 38, 36],
        [85, 97,  3]]])

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [33]:
m = np.random.randint(low = 100, size = (10, 10)) 
print(m)
print(np.min(m))
print(np.max(m))

[[92 62 54 22  7 33 47  8 44 39]
 [68 54 13  9 34 56 56  5 89 66]
 [79 68 51 44 57 21 78  7 15 18]
 [31  0  5 35 83 81 18 77 41  2]
 [35 48 74 38 40 63 74  7 97 40]
 [26 75 42 19 74 91 74 26 14 36]
 [32 34 73 62 30 66 21 34 45 90]
 [39 83  0  2 85 57  4 34 39 38]
 [38  8 55 90 18 33 40  4 39 48]
 [ 0 41 53 48 60 81 66 94 60 71]]
0
97


#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [40]:
m = np.random.randint(low = 100, size = (5, 5))
for i in range(1, len(m)):
    m[i][i-1] = i
print(m)

[[51 99 44 85 60]
 [ 1 78 29  2 92]
 [50  2 66 31 31]
 [ 6 12  3 61 85]
 [ 8 52 86  4 66]]


#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [82]:
m = np.random.randint(low = 100, size = (5, 5))
print(m)
print()
print(m.sum())

[[21 20 30 50 56]
 [17 71 41 66 23]
 [69 81 56 15 94]
 [93 10 77 10 91]
 [ 9 95 22 95 32]]

1244


#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [84]:
m = np.random.randint(low = 100, size = (5, 5))
print(m)
print()
print(m.mean())

[[98 31 48 47  8]
 [ 6 97 17 26 94]
 [59 60 23 11 98]
 [79 23  2 75 16]
 [12 57 15 96 11]]

44.36


#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

In [21]:
l = [x for x in range(11)]
len(l)

11

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

In [94]:
np.random.random((10, 1))

array([[0.63055262],
       [0.56028671],
       [0.31741806],
       [0.9320221 ],
       [0.56720687],
       [0.530731  ],
       [0.13313458],
       [0.92706904],
       [0.46421381],
       [0.56721906]])

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [125]:
a = np.random.randint(low = 2, size = (5, 1))
b = np.random.randint(low = 2, size = (5, 1))
print(a)
print()
print(b)
print()
print(True if np.array_equal(a, b) else False)

[[1]
 [0]
 [0]
 [0]
 [1]]

[[0]
 [1]
 [1]
 [1]
 [0]]

False


#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

In [76]:
m = np.random.uniform(low = 0.0, high = 10.0, size=(10, 1))
print(m)
print()
print(m.astype(int))

[[8.28682007]
 [6.69485813]
 [5.91226577]
 [7.8855279 ]
 [4.3000925 ]
 [9.13006287]
 [8.02144274]
 [5.09597762]
 [8.09628888]
 [2.04141495]]

[[8]
 [6]
 [5]
 [7]
 [4]
 [9]
 [8]
 [5]
 [8]
 [2]]


#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

In [87]:
m = np.random.randint(low = 100, size = (5, 5))
print(m)
row_sums = m.sum(axis = 1)
new_matrix = m / row_sums[:, np.newaxis]
print()
print(new_matrix)

[[86 44 32 16  7]
 [60 90 51 39 36]
 [80 97 75 94 56]
 [25 17 15 20 65]
 [93 91 56 56 22]]

[[0.46486486 0.23783784 0.17297297 0.08648649 0.03783784]
 [0.2173913  0.32608696 0.18478261 0.14130435 0.13043478]
 [0.19900498 0.24129353 0.18656716 0.23383085 0.13930348]
 [0.17605634 0.11971831 0.1056338  0.14084507 0.45774648]
 [0.29245283 0.28616352 0.17610063 0.17610063 0.06918239]]


#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

In [88]:
m = np.random.randint(low = 100, size = (5, 5))
print(m)
print()
print(m.T)

[[15 13 75 30 59]
 [57 69 15 38 66]
 [92 19 82 49 66]
 [83 15  0 75 68]
 [74 40 34 13 27]]

[[15 57 92 83 74]
 [13 69 19 15 40]
 [75 15 82  0 34]
 [30 38 49 75 13]
 [59 66 66 68 27]]


#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

In [92]:
lines, columns = 5, 5
m = np.random.randint(low = 100, size = (lines, columns))
print(m)
m[np.random.randint(lines)][np.random.randint(columns)] = np.random.randint(100)
print()
print(m)

[[47 82 47  8 37]
 [34 47 39 26 32]
 [57  7 88 73 54]
 [ 8 12 63 97 19]
 [72 53 37 66  6]]

[[47 82 47  8 37]
 [34 47 39 26 32]
 [57  7 88 73 54]
 [ 8 12 63 97 97]
 [72 53 37 66  6]]


#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)