In [3]:
import numpy as np
import pandas as pd
url = 'https://bit.ly/tx-data'
df = pd.read_csv(url)

In [5]:
df.head()

transaction_id first_name  last_name       ip_address   amount
0      50563-403     Jacobo   Haresign    18.144.134.48  $647.77
1     54569-3911    Christy       Derl  254.107.123.242  $460.47
2     59667-0024     Florie     Prewer    148.80.11.233  $565.38
3      60429-123     Danika     Shimuk   233.91.221.158  $794.76
4      0187-0771   Annelise  Antonescu   238.143.41.105  $790.41

In [8]:
X = np.array([1, 2, 3, 4, 5])
X

array([1, 2, 3, 4, 5])

In [10]:
mask = np.array([False, False, True, False, True])
mask

array([False, False,  True, False,  True])

In [11]:
X[mask]

array([3, 5])

In [16]:
X % 2 == 0

array([False,  True, False,  True, False])

In [14]:
pair = X % 2 == 0

In [15]:
X[pair]

array([2, 4])

In [36]:
df[df.duplicated()].head() # Affiche les lignes en duplicatas

transaction_id first_name   last_name       ip_address   amount
15      68180-751     Marlon      Fernie   61.133.100.141  $974.30
19      53942-299      Upton        Emig  103.190.123.125  $759.53
20      60289-247      Corri  Rockcliffe    46.150.208.18    $5.68
28     59667-0024     Florie      Prewer    148.80.11.233  $565.38
32      65862-207     Alvira      Heifer   141.170.128.72  $584.13

In [35]:
df[df.duplicated(keep = False)].head() # Affiche les lignes en duplicatas et leurs originaux

transaction_id first_name   last_name       ip_address   amount
2      59667-0024     Florie      Prewer    148.80.11.233  $565.38
5       53942-299      Upton        Emig  103.190.123.125  $759.53
7       60289-247      Corri  Rockcliffe    46.150.208.18    $5.68
12      68180-751     Marlon      Fernie   61.133.100.141  $974.30
14      65862-207     Alvira      Heifer   141.170.128.72  $584.13

In [34]:
duplicatas = df.duplicated(keep = False, subset = ["transaction_id"]) # keep = "first" (défault), "last" ou False
df[duplicatas].head() # Il est préférable de garder le keep en false si on utilise le subset

transaction_id first_name   last_name       ip_address   amount
2      59667-0024     Florie      Prewer    148.80.11.233  $565.38
5       53942-299      Upton        Emig  103.190.123.125  $759.53
7       60289-247      Corri  Rockcliffe    46.150.208.18    $5.68
12      68180-751     Marlon      Fernie   61.133.100.141  $974.30
14      65862-207     Alvira      Heifer   141.170.128.72  $584.13

In [33]:
df[duplicatas].sort_values('transaction_id').head()

transaction_id first_name last_name       ip_address   amount
16      0066-0508       Jedd   Hartman     21.55.247.91  $749.96
42      0066-0508       Jedd   Hartman     21.55.247.91  $749.96
5       53942-299      Upton      Emig  103.190.123.125  $759.53
19      53942-299      Upton      Emig  103.190.123.125  $759.53
2      59667-0024     Florie    Prewer    148.80.11.233  $565.38

In [41]:
df.drop_duplicates(subset = ['transaction_id'], inplace = True)

In [43]:
df.head(16) # La ligne 15 qui était un doublon à été supprimée

transaction_id first_name   last_name       ip_address   amount
0       50563-403     Jacobo    Haresign    18.144.134.48  $647.77
1      54569-3911    Christy        Derl  254.107.123.242  $460.47
2      59667-0024     Florie      Prewer    148.80.11.233  $565.38
3       60429-123     Danika      Shimuk   233.91.221.158  $794.76
4       0187-0771   Annelise   Antonescu   238.143.41.105  $790.41
5       53942-299      Upton        Emig  103.190.123.125  $759.53
6       41163-519    Rachael     Housley    3.188.252.248  $871.72
7       60289-247      Corri  Rockcliffe    46.150.208.18    $5.68
8       0527-1742     Ambros    Goulding   174.124.224.39  $726.12
9       57237-083       Roma     Addekin     37.14.63.174  $526.89
10      60758-060    Auberon       Boxen     168.0.223.98  $309.65
11     43857-0289     Cesare   Andriolli    244.204.3.163  $746.23
12      68180-751     Marlon      Fernie   61.133.100.141  $974.30
13      43319-040  Gavrielle      Vittet    180.20.70.166  $994.20
14      65862-207     Alvira      Heifer   141.170.128.72  $584.13
16      0066-0508       Jedd     Hartman     21.55.247.91  $749.96